### ISSUE TITLE
Update software on Lab PCs and Laptops

### ISSUE THREAD

**Issue by aidan-mundy** [246overclocked/2022-Robot-Code-Java#4]
- https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/frc-game-tools.html
   - https://www.ni.com/en-us/support/downloads/drivers/download.frc-game-tools.html#440024
- https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/wpilib-setup.html
   - https://github.com/wpilibsuite/allwpilib/releases/tag/v2022.1.1
- https://docs.revrobotics.com/rev-control-system/managing-the-control-system/rev-hardware-client
- https://github.com/CrossTheRoadElec/Phoenix-Releases/releases

- [x] left table left lab PC
- [x] left table right lab PC

**Comment by aidan-mundy** [comment]
Left side lab PC is working now, and can be updated. Right side lab PC and the laptops are still in limbo

**Comment by citrus-melon** [comment]
Left lab PC updated, still waiting for right PC
